on: push
jobs:
  build-and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: troyodia/arm-none-eabi-10.3:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: make
      - run: make cppcheck
